name: CI/CD Pipeline for Spring Boot Application Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set Environment Variables
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: echo "Environment variables set."

      - name: Build with Maven
        working-directory: src/main/java/demo
        run: mvn clean package -DskipTests

      - name: Start Test Database
        run: |
          docker run --name test-mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=test_db -e MYSQL_USER=test_user -e MYSQL_PASSWORD=test_password -p 3306:3306 -d mysql:latest
          sleep 30 # Wait for MySQL to initialize

      - name: Verify Database Connection
        run: |
          docker exec test-mysql mysql -u test_user -ptest_password -e "SHOW DATABASES;"
          echo "Database connection verified."

      - name: Run Tests
        working-directory: src/main/java/demo
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: test_db
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
        run: mvn test

      - name: Cleanup Docker Containers
        run: |
          docker stop test-mysql
          docker rm test-mysql

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip curl

      - name: Install or Update AWS CLI
        run: |
          if ! command -v aws >/dev/null; then
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -o awscliv2.zip
            sudo ./aws/install
          else
            echo "AWS CLI found. Updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -o awscliv2.zip
            sudo ./aws/install --update
          fi

      - name: Wait for Environment to be Ready
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          until [ "$(aws elasticbeanstalk describe-environments --environment-names my-env-name --query 'Environments[0].Status' --output text)" = "Ready" ]; do
            echo "Waiting for environment to be ready..."
            sleep 30
          done

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: eb deploy my-env-name